 version: '2'

 services:
  angular: # name of the first service
   build: forumangular
   networks:
    - net
   ports:
    - "4201:4201" # specify port forewarding
   volumes:
    - ./forumangular:/app
  
  php:
   build: forumphp # name of the first service
   networks:
    - net
   links:
    - db:db 
   volumes:
    - ./forumphp:/var/www/html
   ports:
    - 8000:80

  db:
   image: mysql
   volumes:
    - ./mysql:/var/lib/mysql
   networks:
    - net
   environment:
    MYSQL_ROOT_PASSWORD: theo
   ports:
    - "3306:3306"

  phpmyadmin:
   image: phpmyadmin/phpmyadmin
   networks:
    - net
   depends_on:
    - db
   ports:
    - "8080:80"

 
 networks:
  net:
   driver: bridge
